# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='CDEMessages.proto',
  package='com.udtx',
  serialized_pb='\n\x11\x43\x44\x45Messages.proto\x12\x08\x63om.udtx\"\xae\x01\n\nCDEMessage\x12\x11\n\tnode_dcid\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x63rn\x18\x02 \x02(\x05\x12\x10\n\x08trans_id\x18\x03 \x01(\t\x12\x31\n\x10\x61\x63tivate_message\x18\xf4\x03 \x01(\x0b\x32\x16.com.udtx.NodeActivate\x12:\n\x11\x61\x63tivate_response\x18\xf5\x03 \x01(\x0b\x32\x1e.com.udtx.NodeActivateResponse\"3\n\x0cNodeActivate\x12\x10\n\x08node_dna\x18\x01 \x02(\x03\x12\x11\n\tnode_name\x18\x02 \x01(\t\"S\n\x14NodeActivateResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x02(\x08\x12\x12\n\nerror_code\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x01(\t')




_CDEMESSAGE = descriptor.Descriptor(
  name='CDEMessage',
  full_name='com.udtx.CDEMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='node_dcid', full_name='com.udtx.CDEMessage.node_dcid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dcrn', full_name='com.udtx.CDEMessage.dcrn', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='trans_id', full_name='com.udtx.CDEMessage.trans_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='activate_message', full_name='com.udtx.CDEMessage.activate_message', index=3,
      number=500, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='activate_response', full_name='com.udtx.CDEMessage.activate_response', index=4,
      number=501, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=206,
)


_NODEACTIVATE = descriptor.Descriptor(
  name='NodeActivate',
  full_name='com.udtx.NodeActivate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='node_dna', full_name='com.udtx.NodeActivate.node_dna', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='node_name', full_name='com.udtx.NodeActivate.node_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=208,
  serialized_end=259,
)


_NODEACTIVATERESPONSE = descriptor.Descriptor(
  name='NodeActivateResponse',
  full_name='com.udtx.NodeActivateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='accepted', full_name='com.udtx.NodeActivateResponse.accepted', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error_code', full_name='com.udtx.NodeActivateResponse.error_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error_message', full_name='com.udtx.NodeActivateResponse.error_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=261,
  serialized_end=344,
)

_CDEMESSAGE.fields_by_name['activate_message'].message_type = _NODEACTIVATE
_CDEMESSAGE.fields_by_name['activate_response'].message_type = _NODEACTIVATERESPONSE
DESCRIPTOR.message_types_by_name['CDEMessage'] = _CDEMESSAGE
DESCRIPTOR.message_types_by_name['NodeActivate'] = _NODEACTIVATE
DESCRIPTOR.message_types_by_name['NodeActivateResponse'] = _NODEACTIVATERESPONSE

class CDEMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CDEMESSAGE
  
  # @@protoc_insertion_point(class_scope:com.udtx.CDEMessage)

class NodeActivate(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NODEACTIVATE
  
  # @@protoc_insertion_point(class_scope:com.udtx.NodeActivate)

class NodeActivateResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NODEACTIVATERESPONSE
  
  # @@protoc_insertion_point(class_scope:com.udtx.NodeActivateResponse)

# @@protoc_insertion_point(module_scope)
